name: deferred_components
description: A new Flutter project.
publish_to: "none"

version: 1.0.5+6

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  components_module:
    path: ./modules/components_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  deferred-components:
    - name: component
      libraries:
        - package:components_module/components_module.dart
