name: deferred_components
description: A new Flutter project.
publish_to: "none"

version: 1.2.1+15

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  get: ^4.6.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  shared_preferences: ^2.0.12

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4
  mockito: ^5.0.17

flutter:
  uses-material-design: true

  assets:
    - "assets/"

  deferred-components:
    - name: cart
      libraries:
        # Screen
        - "package:deferred_components/feature/screens/cart_screen/page/cart_page.dart"
        - "package:deferred_components/feature/screens/cart_screen/controller/cart_controller.dart"
        - "package:deferred_components/feature/screens/cart_screen/widgets/add_decrease_button.dart"
      assets:
        - "assets/cosmetics.png"
        - "assets/headphone.png"
        - "assets/shoes.png"

    - name: detail
      libraries:
        - "package:deferred_components/feature/screens/detail_screen/arguments/detail_arguments.dart"
        - "package:deferred_components/feature/screens/detail_screen/controller/detail_controller.dart"
        - "package:deferred_components/feature/screens/detail_screen/page/detail_page.dart"
